feat: main

diff --git a/tasks/execute-ansible.yaml b/tasks/execute-ansible.yaml
--- a/tasks/execute-ansible.yaml
+++ b/tasks/execute-ansible.yaml
@@ -4,14 +4,14 @@ kind: Task
 metadata:
   name: execute-ansible-playbooks
   labels:
-    app.kubernetes.io/version: "0.5"
+    app.kubernetes.io/version: "0.6"
   annotations:
     tekton.dev/categories: "configuration-mgmt"
     tekton.dev/pipelines.minVersion: "0.17.0"
     tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
     tekton.dev/tags: "image-build"
 spec:
-  description: execute ansible
+  description: execute ansible playbooks with enhanced security and error handling
   workspaces:
     - name: source
       description: holds the working data
@@ -73,6 +73,14 @@ spec:
       description: the image on which ansible will run
       type: string
       default: "eu.gcr.io/stuttgart-things/sthings-ansible:11.0.0"
+    - name: ANSIBLE_VERBOSITY
+      description: ansible verbosity level (0-4, where 0 is minimal)
+      type: string
+      default: "2"
+    - name: VALIDATE_INVENTORY
+      description: validate inventory before running playbooks
+      type: string
+      default: "true"
     - name: vault-secret-key-addr
       description: vault addr key in the secret
       type: string
@@ -93,7 +101,6 @@ spec:
       description: name of the vault secret
       type: string
       default: "vault"
-    # Add new parameters for ansible credentials secret
     - name: ansible-credentials-secret-name
       description: name of the secret containing ansible credentials
       type: string
@@ -106,6 +113,9 @@ spec:
       description: key for ansible password in the secret
       type: string
       default: "ANSIBLE_PASSWORD"
+  results:
+    - name: playbooks-executed
+      description: number of playbooks successfully executed
   stepTemplate:
     workingDir: $(workspaces.source.path)/$(params.SUB_DIRECTORY)
     image: "$(params.WORKING_IMAGE)"
@@ -119,41 +129,40 @@ spec:
         - $(params.INVENTORY_VARS[*])
       script: |
         #!/usr/bin/env sh
-
         set -eu
 
-        echo "creating vars file"
+        echo "Creating vars file"
         rm -rf ./vars.yaml
-        echo "---" >> ./vars.yaml
+        echo "---" > ./vars.yaml
 
         if [ "$(params.CREATE_INVENTORY)" = "true" ] ; then
+          echo "inventory_groups:" >> ./vars.yaml
+          echo "  host_groups:" >> ./vars.yaml
 
-        echo -e "inventory_groups:\n  host_groups:" >> ./vars.yaml
+          for param in "$@"
+          do
+            group=$(echo "$param" | cut -d "+" -f1)
+            host=$(echo "$param" | cut -d "+" -f2)
+            echo "Processing group: $group"
+            echo "Processing host: $host"
 
-        for param in "$@"
-        do
-          group=$(echo "$param" | cut -d "+" -f1)
-          host=$(echo "$param" | cut -d "+" -f2)
-          echo $group
-          echo $host
+            if [[ $host =~ \[\".*\"\] ]]; then
+              echo "String is already correctly formatted: $host"
+            else
+              echo "Formatting string: $host"
+              host=$(echo "$host" | sed 's/\[/\[\"/g; s/\]/\"]/g')
+            fi
 
-          if [[ $host =~ \[\".*\"\] ]]; then
-              echo "STRING IS ALREADY CORRECTLY FORMATTED: $host"
-          else
-              echo "STRING IS NOT CORRECTLY FORMATTED: $host"
-              host=$(echo $host | sed 's/\[/\[\"/g; s/\]/\"]/g')
-          fi
-
-          echo $host
-
-          yq -i '.inventory_groups.host_groups.'$(echo ${group})' += '$(echo ${host})'' ./vars.yaml
-        done
-
+            echo "Final host value: $host"
+            yq -i '.inventory_groups.host_groups.'"${group}"' += '"${host}" ./vars.yaml
+          done
         else
-          echo "SKIPPED CREATING EXTENDED INVENTORY"
+          echo "Skipped creating extended inventory"
         fi
 
+        echo "Contents of vars.yaml:"
         cat ./vars.yaml
+
     - name: create-vars-file
       args:
         - $(params.EXTRA_VARS[*])
@@ -161,9 +170,14 @@ spec:
         #!/usr/bin/env sh
         set -eu
 
-        for argument in "$@"; do echo $argument | sed -e "s/+-/: /g" >> vars.yaml ; done
+        echo "Adding extra vars to vars.yaml"
+        for argument in "$@"; do
+          echo "$argument" | sed -e "s/+-/: /g" >> vars.yaml
+        done
 
+        echo "Current vars.yaml contents:"
         cat ./vars.yaml
+
     - name: merge-vars-file
       env:
         - name: VARS_FILE
@@ -172,16 +186,20 @@ spec:
         #!/usr/bin/env sh
         set -eu
 
-        if [[ -z "${VARS_FILE}" ]]; then
-          echo "(EXTRA) VARS FILE IS EMPTY - MERGING NOTHING!"
+        if [ -z "${VARS_FILE}" ]; then
+          echo "Extra vars file is empty - nothing to merge"
         else
-          echo ${VARS_FILE} | base64 -d > ./to-be-merged.yaml
-          echo "TO BE MERGED (FROM B64 VALUE):"
+          echo "Decoding and merging vars file from base64"
+          echo "${VARS_FILE}" | base64 -d > ./to-be-merged.yaml
+
+          echo "Contents to be merged:"
           cat ./to-be-merged.yaml
+
           yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' ./vars.yaml ./to-be-merged.yaml -i
+          rm -f ./to-be-merged.yaml
         fi
 
-        echo "MERGED VARS FILE:"
+        echo "Final merged vars.yaml:"
         cat ./vars.yaml
 
     - name: install-roles
@@ -192,17 +210,27 @@ spec:
         set -eu
 
         if [ "$(params.INSTALL_EXTRA_ROLES)" = "true" ] ; then
-          echo "YOU KNOW.. FOR INSTALLING ADDITIONAL ROLES"
+          echo "Installing additional Ansible roles"
+
+          mkdir -p ./roles
 
           for param in "$@"
           do
-            ansible-galaxy install git+${param} -f --roles-path ./roles
-            ls -lta ./roles
+            echo "Installing role from: ${param}"
+            if ansible-galaxy install "git+${param}" -f --roles-path ./roles; then
+              echo "Successfully installed role from ${param}"
+            else
+              echo "ERROR: Failed to install role from ${param}"
+              exit 1
+            fi
           done
 
+          echo "Installed roles:"
+          ls -lta ./roles
         else
-          echo "SKIPPED INSTALLING ADDITIONAL ROLES"
+          echo "Skipped installing additional roles"
         fi
+
     - name: install-collections
       args:
         - $(params.EXTRA_COLLECTIONS[*])
@@ -211,32 +239,63 @@ spec:
         set -eu
 
         if [ "$(params.INSTALL_EXTRA_COLLECTIONS)" = "true" ] ; then
-          echo "you know.. for installing additional collections"
+          echo "Installing additional Ansible collections"
+
+          mkdir -p ./collections
 
           for param in "$@"
           do
-            ansible-galaxy collection install ${param} -f -p ./collections
-            ls -lta ./collections/ansible_collections
+            echo "Installing collection: ${param}"
+            if ansible-galaxy collection install "${param}" -f -p ./collections; then
+              echo "Successfully installed collection ${param}"
+            else
+              echo "ERROR: Failed to install collection ${param}"
+              exit 1
+            fi
           done
 
+          echo "Installed collections:"
+          ls -lta ./collections/ansible_collections 2>/dev/null || echo "No collections directory found"
         else
-          echo "SKIPPED INSTALLING ADDITIONAL COLLECTIONS"
+          echo "Skipped installing additional collections"
         fi
 
     - name: create-inventory-file
       env:
         - name: INVENTORY
           value: $(params.INVENTORY)
-      script: |-
+      script: |
         #!/usr/bin/env sh
         set -eu
 
-        if [[ -z "${INVENTORY}" ]]; then
-          echo "INVENTORY IS EMPTY - CREATING DEFAULT INVENTORY"
-          touch ./inventory
+        if [ -z "${INVENTORY}" ]; then
+          echo "Inventory is empty - creating default inventory"
+          echo "[all]" > ./inventory
+          echo "localhost ansible_connection=local" >> ./inventory
         else
-          echo ${INVENTORY} | base64 -d > ./inventory
+          echo "Decoding inventory from base64"
+          echo "${INVENTORY}" | base64 -d > ./inventory
+          echo "Inventory file contents:"
           cat ./inventory
+        fi
+
+    - name: validate-inventory
+      script: |
+        #!/usr/bin/env sh
+        set -eu
+
+        if [ "$(params.VALIDATE_INVENTORY)" = "true" ]; then
+          echo "Validating inventory file"
+          if ansible-inventory -i ./inventory --list > /dev/null 2>&1; then
+            echo "Inventory validation successful"
+          else
+            echo "ERROR: Inventory validation failed"
+            echo "Inventory contents:"
+            cat ./inventory
+            exit 1
+          fi
+        else
+          echo "Skipped inventory validation"
         fi
 
     - name: run-ansible-playbook
@@ -247,7 +306,6 @@ spec:
           value: "False"
         - name: HOME
           value: $(params.USER_HOME)
-        # Add ANSIBLE_USER and ANSIBLE_PASSWORD from secret
         - name: ANSIBLE_USER
           valueFrom:
             secretKeyRef:
@@ -265,49 +323,116 @@ spec:
             secretKeyRef:
               key: $(params.vault-secret-key-addr)
               name: $(params.vault-secret-name)
+              optional: true
         - name: VAULT_NAMESPACE
           valueFrom:
             secretKeyRef:
               key: $(params.vault-secret-key-namespace)
               name: $(params.vault-secret-name)
+              optional: true
         - name: VAULT_ROLE_ID
           valueFrom:
             secretKeyRef:
               key: $(params.vault-secret-key-approleId)
               name: $(params.vault-secret-name)
+              optional: true
         - name: VAULT_SECRET_ID
           valueFrom:
             secretKeyRef:
               key: $(params.vault-secret-key-approleSecret)
               name: $(params.vault-secret-name)
-      script: |-
+              optional: true
+      script: |
         #!/usr/bin/env sh
         set -eu
 
-        echo "LIST INSTALLED ROLES"
-        if [ -d "roles" ]; then cp -R roles/* ${HOME}/.ansible/roles/ ; fi
-        ansible-galaxy role list
+        # Setup Ansible directories
+        mkdir -p "${HOME}/.ansible/roles"
+        mkdir -p "${HOME}/.ansible/collections"
 
-        echo "LIST INSTALLED COLLECTIONS"
-        if [ -d "collections" ]; then cp -R collections/* ${HOME}/.ansible/collections/ ; fi
-        ansible-galaxy collection list
-
-        echo "YOU KNOW.. FOR RUNNING A PLAYBOOK OR 2"
-
-        # Build extra vars string conditionally using environment variables directly
-        EXTRA_VARS=""
-        if [ -n "${ANSIBLE_USER:-}" ] && [ -n "${ANSIBLE_PASSWORD:-}" ]; then
-            EXTRA_VARS="$EXTRA_VARS -e ansible_user='${ANSIBLE_USER}'"
-            EXTRA_VARS="$EXTRA_VARS -e ansible_password='${ANSIBLE_PASSWORD}'"
+        echo "Installing roles and collections to home directory"
+        if [ -d "roles" ]; then
+          cp -R roles/* "${HOME}/.ansible/roles/"
+          echo "Installed roles:"
+          ansible-galaxy role list
         fi
+
+        if [ -d "collections" ]; then
+          cp -R collections/* "${HOME}/.ansible/collections/"
+          echo "Installed collections:"
+          ansible-galaxy collection list
+        fi
+
+        # Create secure credentials file if credentials are provided
+        CREDS_FILE=""
+        if [ -n "${ANSIBLE_USER:-}" ] && [ -n "${ANSIBLE_PASSWORD:-}" ]; then
+          echo "Setting up Ansible credentials securely"
+          CREDS_FILE="${HOME}/.ansible_creds.yml"
+          cat > "${CREDS_FILE}" <<EOF
+        ansible_user: "${ANSIBLE_USER}"
+        ansible_password: "${ANSIBLE_PASSWORD}"
+        ansible_become_password: "${ANSIBLE_PASSWORD}"
+        EOF
+          chmod 600 "${CREDS_FILE}"
+        fi
+
+        # Build verbosity flag
+        VERBOSITY=""
+        if [ "$(params.ANSIBLE_VERBOSITY)" != "0" ]; then
+          VERBOSITY=$(printf 'v%.0s' $(seq 1 $(params.ANSIBLE_VERBOSITY)))
+          VERBOSITY="-${VERBOSITY}"
+        fi
+
+        echo "Starting playbook execution"
+        PLAYBOOKS_EXECUTED=0
 
         for playbook in "$@"
         do
-          ansible-playbook -vv \
-          -i $(workspaces.source.path)/$(params.SUB_DIRECTORY)/inventory \
-          -e inv_path=$(workspaces.source.path)/$(params.SUB_DIRECTORY)/inventory \
-          -e target_host=$(params.TARGET_HOST) \
-          -e path_to_vars_file=$(workspaces.source.path)/$(params.SUB_DIRECTORY)/vars \
-          $EXTRA_VARS \
-          $playbook
+          # Validate playbook exists
+          if [ ! -f "$playbook" ]; then
+            echo "ERROR: Playbook not found: $playbook"
+            exit 1
+          fi
+
+          echo "=========================================="
+          echo "Executing playbook: $playbook"
+          echo "=========================================="
+
+          # Build ansible-playbook command
+          ANSIBLE_CMD="ansible-playbook ${VERBOSITY} \
+            -i $(workspaces.source.path)/$(params.SUB_DIRECTORY)/inventory \
+            -e inv_path=$(workspaces.source.path)/$(params.SUB_DIRECTORY)/inventory \
+            -e target_host=$(params.TARGET_HOST) \
+            -e path_to_vars_file=$(workspaces.source.path)/$(params.SUB_DIRECTORY)/vars.yaml"
+
+          # Add credentials file if it exists
+          if [ -n "${CREDS_FILE}" ]; then
+            ANSIBLE_CMD="${ANSIBLE_CMD} --extra-vars @${CREDS_FILE}"
+          fi
+
+          # Add playbook path
+          ANSIBLE_CMD="${ANSIBLE_CMD} ${playbook}"
+
+          # Execute playbook
+          if eval ${ANSIBLE_CMD}; then
+            echo "Successfully executed playbook: $playbook"
+            PLAYBOOKS_EXECUTED=$((PLAYBOOKS_EXECUTED + 1))
+          else
+            echo "ERROR: Failed to execute playbook: $playbook"
+            # Cleanup credentials file before exit
+            [ -n "${CREDS_FILE}" ] && rm -f "${CREDS_FILE}"
+            exit 1
+          fi
         done
+
+        # Cleanup credentials file
+        if [ -n "${CREDS_FILE}" ]; then
+          rm -f "${CREDS_FILE}"
+          echo "Cleaned up credentials file"
+        fi
+
+        # Write results
+        echo -n "${PLAYBOOKS_EXECUTED}" > $(results.playbooks-executed.path)
+        echo "=========================================="
+        echo "Execution complete: ${PLAYBOOKS_EXECUTED} playbook(s) executed successfully"
+        echo "=========================================="
